excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running

line_length:
  warning: 200
  error: 350
  ignores_comments: true
  ignores_urls: true

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
