# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewProject
pod 'SwiftLint'
pod 'Alamofire', '~> 5.0'
pod 'MBProgressHUD', '~> 1.2.0'
end
